# Generated by Django 4.1.2 on 2022-11-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'دسته بندی لینک های پایین صفحه',
                'verbose_name_plural': 'دسته بندی های لینک های پایین صفحه',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام سایت')),
                ('site_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='دامنه سایت')),
                ('about_us', models.TextField(blank=True, null=True, verbose_name='درباره ما')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone_number', models.IntegerField(blank=True, null=True, verbose_name='تلفن')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس')),
                ('copy_right', models.CharField(max_length=100, verbose_name='متن کپی رایت')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='images/site_setting', verbose_name='لوگو سایت')),
                ('is_main_setting', models.BooleanField(blank=True, default=False, null=True, verbose_name='تنظیمات اصلی / آزاد')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت ها',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='لینک')),
                ('footer_link_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_module.footerlinkbox', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'لینک پایین صفحه',
                'verbose_name_plural': 'لینک های پایین صفحه',
            },
        ),
    ]
