# Generated by Django 4.1.2 on 2022-11-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_alter_sitesetting_is_main_setting_headerpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headerpage',
            options={'verbose_name': 'لینک سر صفحه', 'verbose_name_plural': 'لینک های سر صفحه ها'},
        ),
        migrations.RemoveField(
            model_name='headerpage',
            name='footer_link_box',
        ),
    ]
