# Generated by Django 4.1.2 on 2022-11-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_alter_sitesetting_site_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/site_setting', verbose_name='لوگو سایت'),
        ),
    ]
