# Generated by Django 4.1.2 on 2022-11-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_alter_sitesetting_site_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
    ]
