# Generated by Django 4.1.2 on 2022-11-02 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_abilityuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilityuser',
            name='Percentage',
            field=models.DecimalField(decimal_places=0, max_digits=3, max_length=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد'),
        ),
    ]
