# Generated by Django 4.1.2 on 2022-11-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_alter_abilityuser_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about_user',
        ),
        migrations.AddField(
            model_name='user',
            name='about_user_long',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='درباره کاربر ( کامل )'),
        ),
        migrations.AddField(
            model_name='user',
            name='about_user_short',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='درباره کاربر ( خلاصه )'),
        ),
    ]
