# Generated by Django 4.1.2 on 2022-11-03 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_remove_user_about_user_user_about_user_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, max_length=100, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='سن'),
        ),
    ]
