# Generated by Django 4.1.2 on 2022-11-03 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0006_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50, verbose_name='پایه')),
                ('school', models.CharField(max_length=100, verbose_name='نام دانشگاه / دبیرستان / دبستان')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تحصیل کاربر',
                'verbose_name_plural': 'تحصیلات کاربران',
            },
        ),
    ]
