# Generated by Django 4.1.2 on 2022-11-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0007_user_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_education',
            name='documents',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مدارک'),
        ),
    ]
