# Generated by Django 4.1.2 on 2022-11-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0008_user_education_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_education',
            name='date_end',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='تاریخ پایان تحصیل'),
        ),
        migrations.AddField(
            model_name='user_education',
            name='date_start',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='تاریخ شروع تحصیل'),
        ),
    ]
