# Generated by Django 4.1.2 on 2022-11-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0009_user_education_date_end_user_education_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_user_long',
            field=models.TextField(blank=True, null=True, verbose_name='درباره کاربر ( کامل )'),
        ),
    ]
