# Generated by Django 4.1.2 on 2022-11-14 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0010_alter_user_about_user_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('create_data', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربر')),
            ],
            options={
                'verbose_name': 'پیام کابر',
                'verbose_name_plural': 'پیام های کاربر',
            },
        ),
        migrations.CreateModel(
            name='UserContactAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_message', models.TextField(verbose_name='جوابیه پیام')),
                ('create_data', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_module.usercontactmessage', verbose_name='پیام کاربر')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ارسال کننده (مدیر)')),
            ],
        ),
    ]
