# Generated by Django 4.1.2 on 2022-11-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0013_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontactmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_active_code',
        ),
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='پیام'),
        ),
        migrations.DeleteModel(
            name='UserContactAnswer',
        ),
        migrations.DeleteModel(
            name='UserContactMessage',
        ),
    ]
