# Generated by Django 4.1.2 on 2022-11-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0014_remove_usercontactmessage_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='message',
        ),
    ]
